Fix: selinux: use kernel definition of PF_MAX in scripts
In file included from ../scripts/selinux/mdp/mdp.c:49:
../security/selinux/include/classmap.h:247:2: error: #error New address family defined, please update secclass_map.

In file included from ../scripts/selinux/genheaders/genheaders.c:19:
../security/selinux/include/classmap.h:247:2: error: #error New address family defined, please update secclass_map.

Use linux/socket.h from kernel instead of sys/socket.h from host

https://patchwork.kernel.org/project/selinux/patch/20190312194758.6f411a8b@t440s.fritz.box/